-- Drop all tables if they exist
DROP TABLE IF EXISTS "AcceptedChallenge" CASCADE;
DROP TABLE IF EXISTS "RequiredCapability" CASCADE;
DROP TABLE IF EXISTS "ChallengeTags" CASCADE;
DROP TABLE IF EXISTS "Challenge" CASCADE;
DROP TABLE IF EXISTS "Route" CASCADE;
DROP TABLE IF EXISTS "TransportMedium" CASCADE;
DROP TABLE IF EXISTS "LocationCapabilities" CASCADE;
DROP TABLE IF EXISTS "LocationCapability" CASCADE;
DROP TABLE IF EXISTS "Location" CASCADE;
DROP TABLE IF EXISTS "LocationStatus" CASCADE;
DROP TABLE IF EXISTS "LocationType" CASCADE;
DROP TABLE IF EXISTS "ChallengeTag" CASCADE;
DROP TABLE IF EXISTS "ChallengeType" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "Prize" CASCADE;