TRUNCATE TABLE "ChallengeTag" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ChallengeType" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "LocationStatus" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "LocationType" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "LocationType" RESTART IDENTITY CASCADE;